Больше подробностей (часть 1)
htmlacademy-react/1447627-six-cities-13 pull request #5
Opened 2023-07-29 14:23 UTC by umnyash

2023-07-31 07:06 UTC, n0sfer666 requested changes

2023-07-31 07:06 UTC, n0sfer666 commented on src/components/cities/cities.tsx
> +function Cities({offersCount = Settings.OffersCount, places}: CitiesProps): React.JSX.Element {
Недостаточно в названии такого большого компонента просто слова "Города".
Подумайте какую отвественность вы планируете для этого компонента и лаконично выразите её в названии. (2-3 слова не более)

2023-07-31 07:06 UTC, n0sfer666 commented on src/components/cities/cities.tsx
> +  const currentCityLocation = placesByCurrentCity[0]?.city.location;
**Необязательная правка**
Предположим что-то пошло не так и вы не получили список офферов.
Нужно тут как-то это разрулить. Или не нужно)) на ваше усмотрение.

2023-07-31 07:06 UTC, n0sfer666 commented on src/components/favorites-section/favorites-section.tsx
> +    return (
**Необязательная правка**
Предположим логика усложнилась. Конструкция if-else как и тернарник - не гибкая от слова совсем.
Такие штуки лучше всегда разруливать линейно.
т.е.
```
if (!places || places.length === 0) return ( renderEmptyLayout() )

normalLogic()
```
Тогда при расширении логики модификация текущего кода будет минимальна

2023-07-31 07:06 UTC, n0sfer666 commented on src/hooks/use-map-markers/use-map-markers.ts
> +        iconUrl: MarkerIcon.ActiveTypeUrl,
дублирование кода.
Сделайте вне компонента (но в этом файле) функция типа getIcon в которую в параметре будет залетать iconUrl а остальные будут внутри функции (или необязательные и по дефолту выставляться)
А сами маркеры храните в объектке Icons = {default: (...), current: (...) }

2023-07-31 07:06 UTC, n0sfer666 commented on src/hooks/use-map/use-map.ts
> +const TILE_LAYER = 'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png';
**Необязательная правка**
Константы обычно храняться в отдельном файле.
Внутри этой же папки создайте файл constants.ts и туда всё константы переместите

2023-07-31 07:06 UTC, n0sfer666 commented on src/pages/favorites/favorites.tsx
> +  const isEmpty = !places?.length;
зачем здесь "?"

2023-07-31 18:10 UTC, umnyash commented on src/pages/favorites/favorites.tsx
> +  const isEmpty = !places?.length;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2023-08-01 05:10 UTC, n0sfer666 commented on src/pages/favorites/favorites.tsx
> +  const isEmpty = !places?.length;
я знаю для чего используется "?"
Здесь он зачем?
У вас этот параметр необязателен?

2023-08-01 10:38 UTC, umnyash commented on src/pages/favorites/favorites.tsx
> +  const isEmpty = !places?.length;
Обязательный. Это на случай, если по ошибке будет передан не массив.

2023-08-01 10:41 UTC, umnyash commented on src/pages/favorites/favorites.tsx
> +  const isEmpty = !places?.length;
А может и не обязательный. Мы пока не разбирали как будут формироваться данные избранного. Если избранного нет, то может вообще в компонент не нужно передавать places.

2023-08-01 10:42 UTC, umnyash commented on src/pages/favorites/favorites.tsx
> +  const isEmpty = !places?.length;
С подобными мелочами я разберусь ближе к защите.

2023-08-01 11:11 UTC, merged